<?php
	//Insert and Update example for using Value and Data Access Objects generated by PHP Class Builder
	//Generated By : PHP Class Builder v1.0


	require_once(realpath(dirname( __FILE__ ) )."/../../include.DAO.php"); //A must!

	$user = new User(); //Instantiate a Value Object
	$user->setIdusers(16614); //int(11)
	$user->setFirstName("Dominque Alline Hilton Mora Chia"); //varchar(45)
	$user->setLastName("Myrna Neida"); //varchar(45)


	try{
		$dao = new UsersDao(); //Create a Data Access Object
		$affected = $dao->save($user); //Saves or update (if the record  exists)
		echo "Save succesful! Affected Rows = " . $affected ;
	}catch(Exception $e){
		echo "Save/Update failed<br /><br />";
		echo $e->getMessage();
	}
?>