<?php
	//Delete and Select example for using Value and Data Access Objects generated by PHP Class Builder
	//Generated By : PHP Class Builder v1.0


	require_once(realpath(dirname( __FILE__ ) )."/../../include.DAO.php"); //A must!




	$dao = new UsersDao(); //Create a Data Access Object
	$user = $dao->getByIdusers(17511); //Find Object to delete

	//You can access various properties for the selected object
//	echo "<pre>";
//	if(is_object($user)){
//		echo $user->getIdusers() ."<br />";
//		echo $user->getFirstName() ."<br />";
//		echo $user->getLastName() ."<br />";
//	}
//	echo "</pre>";
	try{
		$affected = $dao->delete($user);
		echo "Delete successful! Affected Rows = " . $affected ;
	}catch(Exception $e){
		echo "Delete failed<br /><br />";
		echo $e->getMessage();
	}
?>