<?php
	//Delete and Select example for using Value and Data Access Objects generated by PHP Class Builder
	//Generated By : PHP Class Builder v1.0


	require_once(realpath(dirname( __FILE__ ) )."/../../include.DAO.php"); //A must!




	$dao = new ProductsDao(); //Create a Data Access Object
	$product = $dao->getByID(1811); //Find Object to delete

	//You can access various properties for the selected object
//	echo "<pre>";
//	if(is_object($product)){
//		echo $product->getID() ."<br />";
//		echo $product->getProductsName() ."<br />";
//		echo $product->getProductImage() ."<br />";
//	}
//	echo "</pre>";
	try{
		$affected = $dao->delete($product);
		echo "Delete successful! Affected Rows = " . $affected ;
	}catch(Exception $e){
		echo "Delete failed<br /><br />";
		echo $e->getMessage();
	}
?>