<?php
	//Insert and Update example for using Value and Data Access Objects generated by PHP Class Builder
	//Generated By : PHP Class Builder v1.0


	require_once(realpath(dirname( __FILE__ ) )."/../../include.DAO.php"); //A must!

	$product = new Product(); //Instantiate a Value Object
	$product->setID(5753); //int(11)
	$product->setProductsName("Rod Chin Janetta Paige Glennis Alline Alline"); //varchar(45)
	$product->setProductImage("Jayme"); //varchar(45)


	try{
		$dao = new ProductsDao(); //Create a Data Access Object
		$affected = $dao->save($product); //Saves or update (if the record  exists)
		echo "Save succesful! Affected Rows = " . $affected ;
	}catch(Exception $e){
		echo "Save/Update failed<br /><br />";
		echo $e->getMessage();
	}
?>